

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  ms-cliente-persona:
    build:
      context: ./ms-cliente-persona
    ports:
      - "8080:8080"
    environment:
      - spring.rabbitmq.host=rabbitmq
    depends_on:
      - rabbitmq

  ms-cuenta-movimiento:
    build:
      context: ./ms-cuenta-movimiento
    ports:
      - "8081:8081"
    environment:
      - spring.rabbitmq.host=rabbitmq
    depends_on:
      - rabbitmq
